Http/routes.php
<?php
Route::group(['domain'=>config('admin.domain'),'middleware' => ['web', 'auth'], 'prefix' => 'admin/blog', 'namespace' => 'Modules\Blog\Http\Controllers'], function()
{
    Route::get('/', 'BlogController@dashboard')
            ->name('panel.dashboard');
    Route::get('/index', 'BlogController@dashboard')
            ->name('panel.dashboard__index');

    // post
    Route::get('/posts', 'BlogController@index')
            ->name('panel.post__index');
    Route::get('/ajaxposts', 'BlogController@ajaxPosts')
            ->name('panel.post__index__ajax');
    Route::get('/post/add', 'BlogController@addPost')
            ->name('panel.post__add');
    Route::post('/post/add', 'BlogController@addPostPost')
            ->name('panel.post__save');
    Route::get('/post/{id}/view', 'BlogController@viewPost')
            ->name('panel.post__view');
    Route::post('/post/{id}/update', 'BlogController@updatePost')
            ->name('panel.post__update');
    Route::get('/post/{id}/remove', 'BlogController@removePost')
            ->name('panel.post__delete');
    Route::post('/post/massdelete', 'BlogController@massdeletePost')
            ->name('panel.post__delete__mass');
    
    // pages
    Route::get('/pages', 'BlogController@pages')
            ->name('panel.page__index');
    Route::get('/ajaxpages', 'BlogController@ajaxPages')
            ->name('panel.page__index__ajax');
    Route::get('/page/add', 'BlogController@addPage')
            ->name('panel.page__add');
    Route::post('/page/add', 'BlogController@addPagePost')
            ->name('panel.page__save');
    Route::get('/page/{id}/view', 'BlogController@viewPage')
            ->name('panel.page__view');
    Route::post('/page/{id}/update', 'BlogController@updatePage')
            ->name('panel.page__update');
    Route::get('/page/{id}/remove', 'BlogController@removePage')
            ->name('panel.page__delete');
    Route::post('/page/massdelete', 'BlogController@massdeletePage')
            ->name('panel.page__delete__mass');

    // trash
    Route::get('/trash', 'BlogController@trash')
            ->name('panel.post.trash__index');
    Route::get('/ajaxtrashposts', 'BlogController@ajaxtrashPosts')
                    ->name('panel.post.trash__delete__ajax');
    Route::get('/trash/{id}/delete', 'BlogController@deleteTrash')
            ->name('panel.post.trash__delete');
    Route::get('/trash/{id}/restore', 'BlogController@restoreTrash')
            ->name('panel.post.trash__update__restore');
    Route::post('/trash/massdelete', 'BlogController@massdeleteTrash')
            ->name('panel.post.trash__delete__mass');
    Route::post('/trash/massrestore', 'BlogController@massrestoreTrash')
            ->name('panel.post.trash__update__restore__mass');
    Route::get('/trash/empty', 'BlogController@emptyTrash')
            ->name('panel.post.trash__delete__clear');

    Route::get('/add-category-post/{name}/{parent}', 'BlogController@store_category_ajax')
            ->name('panel.category__add__ajax__post');
    Route::get('/get-category-post/{post_id}', 'BlogController@get_all_category')
            ->name('panel.category__index__get');
    Route::get('/get-category-parent/{category_id}', 'BlogController@get_category_parent')
            ->name('panel.category__index__getparent');

    // categories
    Route::get('/categories', 'BlogController@categories')
            ->name('panel.category__index');    
    Route::get('/ajaxcategories', 'BlogController@ajaxCategories')
            ->name('panel.category__index__ajax');
    Route::get('/category/add', 'BlogController@addCategory')
            ->name('panel.category__add');
    Route::post('/category/add', 'BlogController@addCategoryPost')
            ->name('panel.category__save');
    Route::post('/category/ajaxadd', 'BlogController@addCategoryPost')
            ->name('panel.category__add__ajax');
    Route::get('/category/{id}/view', 'BlogController@viewCategory')
            ->name('panel.category__view');
    Route::post('/category/{id}/update', 'BlogController@updateCategory')
            ->name('panel.category__update');
    Route::get('/category/{id}/remove', 'BlogController@removeCategory')
            ->name('panel.category__delete');
    Route::post('/category/massdelete', 'BlogController@massdeleteCategory')
            ->name('panel.category__delete__mass');

    // tags
    Route::get('/tags', 'BlogController@tags')
            ->name('panel.tag__index');
    Route::get('/ajaxtags', 'BlogController@ajaxTags')
            ->name('panel.tag__index__ajax');
    Route::get('/tag/add', 'BlogController@addTag')
            ->name('panel.tag__add');
    Route::post('/tag/add', 'BlogController@addTagPost')
            ->name('panel.tag__save');
    Route::get('/tag/{id}/view', 'BlogController@viewTag')
            ->name('panel.tag__view');
    Route::post('/tag/{id}/update', 'BlogController@updateTag')
            ->name('panel.tag__update');
    Route::get('/tag/{id}/remove', 'BlogController@removeTag')
            ->name('panel.tag__delete');
    Route::post('/tag/massdelete', 'BlogController@massdeleteTag')
            ->name('panel.tag__delete__mass');

    // media
    Route::get('/media', 'BlogController@media')
            ->name('panel.media__index');
    Route::get('/get-media', 'BlogController@get_media')
            ->name('panel.media__index__ajax');
    Route::post('/get-media', 'BlogController@get_media')
            ->name('panel.media__index__ajax__post');
    Route::get('/delete-media/{id}', 'BlogController@destroy_media')
            ->name('panel.media__delete');
    Route::post('/store-media', 'BlogController@store_media')
            ->name('panel.media__save');
    Route::post('/bulk-delete-media/', 'BlogController@bulk_delete_media')
            ->name('panel.media__delete__mass');

    Route::get('/site-setting', 'BlogController@site_setting_view')
            ->name('panel.setting.site__index');
    Route::post('/save-setting', 'BlogController@site_setting_save')
            ->name('panel.setting.site__update');
    Route::post('/save-program', 'BlogController@save_program')
            ->name('panel.setting.site__update__program');

    // slider
    Route::get('/slider','BlogController@head_slider')
            ->name('panel.slider__index');
    Route::get('/new-slider','BlogController@new_slider_view')
            ->name('panel.slider__add');
    Route::post('/act-new-slider','BlogController@new_slider_act')
            ->name('panel.slider__save');
    Route::get('/edit-slider/{id}','BlogController@edit_slider_view')
            ->name('panel.slider__view');
    Route::post('/edit-slider/{id}/act_edit_slider','BlogController@edit_slider_act')
            ->name('panel.slider__update');
    Route::get('/hapus-slider/{id}','BlogController@hapus_slider')
            ->name('panel.slider__delete');

    // keywords
    Route::get('/keywords', 'BlogController@keywords')
            ->name('panel.keywords__index');
    Route::get('/get-keywords', 'BlogController@ajaxKeywords')
            ->name('panel.keywords__index__ajax');
    Route::post('/get-keywords', 'BlogController@ajaxKeywords')
            ->name('panel.keywords__index__ajax');
    Route::get('/keywords/add', 'BlogController@addKeyword')
            ->name('panel.keywords__add');
    Route::post('/keywords/add', 'BlogController@addKeywordPost')
            ->name('panel.keywords__save');
    Route::get('/keywords/{id}/view', 'BlogController@viewKeyword')
            ->name('panel.keywords__view');
    Route::post('/keywords/{id}/update', 'BlogController@updateKeyword')
            ->name('panel.keywords__update');
    Route::get('/keywords/{id}/remove', 'BlogController@removeKeyword')
            ->name('panel.keywords__delete');
    Route::post('/keywords/massdelete', 'BlogController@massdeleteKeywords')
            ->name('panel.keywords__delete__mass');

    // users
    Route::get('/users', 'BlogController@users')
            ->name('panel.users__index');
    Route::get('/get-users', 'BlogController@ajaxUsers')
            ->name('panel.users__index__ajax');
    Route::post('/get-users', 'BlogController@ajaxUsers')
            ->name('panel.users__index__ajax');
    Route::get('/users/add', 'BlogController@addUser')
            ->name('panel.users__add');
    Route::post('/users/add', 'BlogController@addUserPost')
            ->name('panel.users__save');
    Route::get('/users/{id}/view', 'BlogController@viewUser')
            ->name('panel.users__view');
    Route::post('/users/{id}/update', 'BlogController@updateUser')
            ->name('panel.users__update');
    Route::get('/users/{id}/remove', 'BlogController@removeUser')
            ->name('panel.users__delete');
});

Route::group(['middleware' => 'web', 'prefix' => 'doc-ui', 'namespace' => 'Modules\Blog\Http\Controllers'], function(){
    Route::get('/','DocController@index');
});

Route::group(['middleware' => 'web', 'prefix' => 'blogs', 'namespace' => 'Modules\Blog\Http\Controllers'], function(){
    Route::get('/','FrontController@index');
    Route::get('/read/{slug_id}','FrontController@single_post')->name('single.post');
    Route::get('/{slug_id}','FrontController@single_page')->name('single.page');
    Route::get('/category/{category_slug}','FrontController@postsCategory')->name('list.post.category');
    Route::get('/tag/{tag_slug}','FrontController@postsTag')->name('list.post.tag');

    //Comment
    Route::post('/go-comment/{id}','FrontController@doInsertComment');
    Route::get('/getcomment/{postid}','FrontController@getPostComment');
});

Route::get('/admin', function(){
    return Redirect::to('/admin/blog');
});

Route::get('/create-sitemap', function(){
    PostHelper::create_sitemap();
    return Redirect::to('/');
});

Route::get('/recreate-sitemap', function(){
    PostHelper::create_sitemap(true);
    return Redirect::to('/');
});

Route::get('index-sitemap.xml', function(){

Entities/Posts.php
<?php

namespace Modules\Blog\Entities;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;

class Posts extends Model
{
	use SoftDeletes;
	
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'posts';
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['*'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * Scope a query to only include posts of a given type.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param mixed $type
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopePostType($query, $type)
    {
        return $query->where('post_type', $type);
    }

    /**
     * Scope a query to only include post of a given status publish and already published.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param mixed $type
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopePublished($query)
    {
        return $query->where('status', 1)
                     ->where('published_at', '<=', Carbon::now());
    }

    /**
     * Get the user that owns the post.
     */
    public function user()
    {
        return $this->belongsTo('App\User', 'author', 'id');
    }

    /**
     * Get the comments for the blog post.
     */
    public function comments()
    {
        return $this->hasMany('Modules\Blog\Entities\Comments', 'post_id');
    }

    /**
     * Get the metas for the blog post.
     */
    public function metas()
    {
        return $this->hasMany('Modules\Blog\Entities\PostMeta', 'post_id');
    }

    /**
     * the categories that belong to the post.
     */
    public function tags()
    {
        return $this->belongsToMany('Modules\Blog\Entities\Tags', 'post_tags', 'post_id', 'tag_id');
    }

    /**
     * the categories that belong to the post.
     */
    public function categories()
    {
        return $this->belongsToMany('Modules\Blog\Entities\Categories', 'post_categories', 'post_id', 'category_id');
    }

    /**
     * Get full slug post.
     */
    public function getFullSlugAttribute($value)
    {
        return $this->slug.'-'.$this->slug_id;
    }

    /**
     * Get post meta_title.
     */
    public function getMetaTitleAttribute($value)
    {
        $meta_title = $this->metas->where('meta_key', 'meta_title')->first()->meta_value ?? $this->title;
        $meta_title = ucwords($meta_title);
        return $meta_title;
    }

    /**
     * Get post meta_desc.
     */
    public function getMetaDescAttribute($value)
    {
        return $this->metas->where('meta_key', 'meta_desc')->first()->meta_value ?? str_limit(html_entity_decode(strip_tags($this->content)), 250);
    }

    /**
     * Get post meta_keyword.
     */
    public function getMetaKeywordAttribute($value)
    {
        return $this->metas->where('meta_key', 'meta_keyword')->first()->meta_value ?? '';
    }
}

Resources/views/admin/categories.blade.php
@extends('blog::layouts.master')

@section('content')
<div class="col-md-12">
<form method="post" action="{{ route('panel.category__delete__mass') }}" accept-charset="UTF-8">
    <a href="{{ route('panel.category__add') }}" class="btn btn-round btn-fill btn-info">New Category +<div class="ripple-container"></div></a>
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <input type="hidden" name="id" class="bulk-delete-id">
    <button type="sumbit" style="display: none;" class="btn btn-round btn-fill btn-danger bulk-delete-item">Delete <span id="bulk-delete-count"></span> Category</button>
</form>
<div class="card">
    <div class="card-header" data-background-color="green">
        <h4 class="title">Category</h4>
        <p class="category">All Category</p>
    </div>

    <div class="card-content table-responsive">
        <table class="table mydatatable" id="table-categories">
            <thead>
                <th>Name</th>
                <th>Created At</th>
                <th>Action</th>
            </thead>
        </table>
    </div>
</div>
</div>
@stop

Resources/views/admin/index.blade.php
@extends('blog::layouts.master')

@section('content')

<div class="col-md-12">
<form method="post" action="{{ route('panel.post__delete__mass') }}" accept-charset="UTF-8">
<a href="{{ route('panel.post__add') }}" class="btn btn-round btn-fill btn-info">New Post +<div class="ripple-container"></div></a>

<input type="hidden" name="_token" value="{{ csrf_token() }}">
<input type="hidden" name="id" class="bulk-delete-id">
<button type="sumbit" style="display: none;" class="btn btn-round btn-fill btn-danger bulk-delete-item">Delete <span class="bulk-delete-count"></span> Post</button>
</form>
<div class="card">
    <div class="card-header" data-background-color="green">
        <h4 class="title">Posts</h4>
        <p class="category">All Post</p>
    </div>

    <div class="card-content table-responsive">
        <table class="table mydatatable" id="posts-table">
            <thead>
                <th>Title</th>
                <th>Author</th>
                <th>Published At</th>
                <th>Action</th>
            </thead>
        </table>
    </div>
</div>
</div>
@stop

Resources/views/admin/keywords.blade.php
@extends('blog::layouts.master')

@section('content')

<div class="col-md-12">
<form method="post" action="{{ route('panel.keywords__delete__mass') }}" accept-charset="UTF-8">
<a href="{{ route('panel.keywords__add') }}" class="btn btn-round btn-fill btn-info">New Keyword +<div class="ripple-container"></div></a>

<input type="hidden" name="_token" value="{{ csrf_token() }}">
<input type="hidden" name="id" class="bulk-delete-id">
<button type="sumbit" style="display: none;" class="btn btn-round btn-fill btn-danger bulk-delete-item">Delete <span class="bulk-delete-count"></span> Keyword</button>
</form>
<div class="card">
    <div class="card-header" data-background-color="green">
        <h4 class="title">Keywords</h4>
        <p class="category">All Keywords</p>
    </div>

    <div class="card-content table-responsive">
        <table class="table mydatatable" id="keywords-table">
            <thead>
                <th>Title</th>
                <th>Slug</th>
                <th>Created At</th>
                <th>Action</th>
            </thead>
        </table>
    </div>
</div>
</div>
@stop

Resources/views/admin/media.blade.php
@extends('blog::layouts.master')

@section('content')
<div class="col-md-12">
<h3>Media</h3>
<h5>Tambah Media</h5>
<div class="btn btn-round btn-fill btn-info" style="margin-bottom: 10px;" onclick="document.getElementById('uploadmedia').click();">Upload media +
    <form id="actuploadmedia" method="post" action="{{ URL::to('/administrator/act-new-media') }}" accept-charset="UTF-8" enctype="multipart/form-data">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="file" id="uploadmedia" name="media[]" style="cursor: pointer;display: none;" multiple>
    </form>
</div>
<form class="pull-right" method="post" action="{{ URL::to($prefix.'bulk-delete-media/')}}" accept-charset="UTF-8">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <input type="hidden" name="id" class="bulk-delete-id">
    <button type="sumbit" style="display: none;margin-bottom: 10px;" class="btn btn-round btn-fill btn-danger bulk-delete-item">Delete <span class="bulk-delete-count"></span> Media</button>
</form>
<a id="canceldelete" style="margin-bottom: 10px;display: none;" onclick="cancelDelete()" class="btn btn-round btn-fill btn-danger pull-right">Cancel Delete</a>
<div class="card">
    <div class="card-content table-responsive">
    <div class="table-overlay">Processing...</div>
        <table class="table mydatatable mediatable" id="MediaTable">
            <thead>
                <th>Preview</th>
                <th>Name</th>
                <th>Created At</th>
            </thead>
        </table>
    </div>
</div>
</div>
@stop
 

Resources/views/admin/page_edit.blade.php
@extends('blog::layouts.master')

@section('content')

<div class="col-md-12">
    @if ($errors->any())
    <div class="alert alert-danger alert-dismissable ">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        There is some error. Please check again
    </div>
    @endif
    <form id="post-form" method="post" action="{{ route('panel.page__update',$page->id) }}" accept-charset="UTF-8">
        <div class="row">           
            <div class="col-md-9"> 
                <h4 class="title">Edit Page</h4>
            </div>
            <div class="col-md-9 col-sm-6 col-xs-6"> 
                <a href="{{ route('panel.page__add') }}" class="btn btn-round btn-fill btn-info">
                    New Page +<div class="ripple-container"></div>
                </a>
                <a target="_blank" href="{{ route('single.page', $page->full_slug) }}" class="btn btn-round btn-fill btn-info">
                    View Page<div class="ripple-container"></div>
                </a>
                <a onclick="return confirm('Delete Page?');" href="{{route('panel.page__delete',$page->id)}}" class="btn btn-round btn-fill btn-danger">
                    Delete Page<div class="ripple-container"></div>
                </a>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-6">
                <button type="submit" class="btn btn-success pull-right">Save Page</button>
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
            </div>
        </div>

        <div class="row" style="margin-top: 15px;">
            <div class="col-md-9">
                <div class="form-group">
                    <label class="control-label">Title</label>
                    @if ($errors->has('title'))
                    <div class="has-error">
                        <span class="help-block">
                            <strong>This field is required</strong>
                        </span>
                    </div>
                    @endif
                    <input class="form-control" type="text" name="title" value="{{ $page->title }}" placeholder="Enter Title Here" required="required">
                </div>

                <a id="browse_media_post" data-toggle="modal" data-target="#myMedia" class="btn btn-round btn-fill btn-default" style="margin-bottom: 10px;">Add Media</a>
                
                <div class="form-group">
                    <label class="control-label">Page Content</label>
                    @if ($errors->has('content'))
                    <div class="has-error">
                        <span class="help-block">
                            <strong>This field is required</strong>
                        </span>
                    </div>
                    @endif
                    <textarea class="form-control mytextarea" name="content">{{ $page->content }}</textarea>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                          SEO Setting <a data-toggle="collapse" href="#post-seo"><i style="float: right;" class="fa fa-caret-down" aria-hidden="true"></i></a>
                        </h4>
                    </div>
                    <div id="post-seo" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <div class="form-group">
                                <label class="control-label">Meta Title</label>
                                <input value="{{ $page_meta->meta_title ?? '' }}" class="form-control" type="text" name="meta_title" maxlength="191">
                            </div>
                            <div class="form-group">
                                <label class="control-label">Meta Deskripsi</label>
                                <textarea class="form-control" id="inputan" name="meta_desc" style="min-height: 100px;" maxlength="300">{{ $page_meta->meta_desc ?? '' }}</textarea>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Keyword</label>
                                <input value="{{ $page_meta->meta_keyword ?? '' }}" class="form-control" type="text" name="meta_keyword" maxlength="191">
                                <small>Contoh : keyword 1, keyword 2, keyword 3</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                          Publish <a data-toggle="collapse" href="#post-status"><i style="float: right;" class="fa fa-caret-down" aria-hidden="true"></i></a>
                        </h4>
                    </div>
                    <div id="post-status" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <div class="form-group">
                                <label>Page Status</label>
                                <select name="status" class="form-control">
                                    <option value="draft" {{ $page->status == 'draft' ? 'selected' : '' }}>Draft</option>
                                    <option value="publish" {{ $page->status == 'publish' ? 'selected' : '' }}>Published</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Date Published</label>
                                <div class="input-group input-append date datetimepicker">
                                    <input class="form-control" size="16" type="text" value="{{ $page->published_at }}" name="published_at" readonly>
                                    <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                @if ( count($templates) > 0 )
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                          Page Template <a data-toggle="collapse" href="#post-template"><i style="float: right;" class="fa fa-caret-down" aria-hidden="true"></i></a>
                        </h4>
                    </div>
                    <div id="post-template" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <div class="form-group">
                                <select name="page_template" class="form-control">
                                    <option value="none" {{ $page_meta->page_template == 'none' || $page_meta->page_template == '' ? 'selected' : '' }}>None</option>
                                    @foreach ($templates as $template)
                                    <option value="{{ $template->file_name }}" {{ $page_meta->page_template == $template->file_name ? 'selected':'' }}>{{ $template->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                @endif

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                          Featured Image <a data-toggle="collapse" href="#post-fimg"><i style="float: right;" class="fa fa-caret-down" aria-hidden="true"></i></a>
                        </h4>
                    </div>
                    <div id="post-fimg" class="panel-collapse collapse in">
                        <div class="panel-body form-group">
                            <a id="browse_fimg_post" data-tujuan="featured_img" data-toggle="modal" data-target="#myFimg" class="btn btn-round btn-fill btn-default" style="margin-bottom: 10px;">Set Featured Image</a>
                            <input type="hidden" name="featured_image" id="featured_img" value="{{ $page->featured_image }}">
                            <div class="preview-fimg-wrap" style="display: {{ $page->featured_image != '' ? 'block' : ''  }};">
                                <div class="preview-fimg" style="background-image: url({{ $page->featured_image }});"></div>
                                <a href="#" onclick="remove_fimg()" class="remove-fimg"><i class="fa fa-times" aria-hidden="true"></i> Remove Featured Image</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>


    </form>

</div>
@stop

@section('modal')
<div class="overlay"></div>

<div class="custom-modal media-modal">
<div class="close-modal" id="close_media_post" data-toggle="modal" data-target="#myModal">X</div>
    
    <div class="card">
        <div class="btn btn-round btn-fill btn-info" style="margin-bottom: 10px;" onclick="document.getElementById('uploadmedia').click();">Upload media +
            <form id="actuploadmedia" method="post" action="{{ URL::to('/administrator/act_new_media') }}" accept-charset="UTF-8" enctype="multipart/form-data">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <input type="file" id="uploadmedia" name="media[]" style="cursor: pointer;display: none;" multiple>
            </form>
        </div>
    <div class="card-content table-responsive">
        <table style="width: 100%;" class="table mediatable" id="MediaPost">
            <thead >
                <th>Preview</th>
                <th>Judul</th>
                <th>Tanggal</th>
                <th>Aksi</th>
            </thead>
        </table>
    </div>
    </div>
</div>

<div class="custom-modal fimg-modal">
<div class="close-modal" id="close_fimg_post" data-toggle="modal" data-target="#myFimg">X</div>
    <div class="card">
        <div class="btn btn-round btn-fill btn-info" style="margin-bottom: 10px;" onclick="document.getElementById('uploadfimg').click();">Upload media +
            <form id="actuploadfimg" method="post" action="{{ URL::to('/administrator/act_new_media') }}" accept-charset="UTF-8" enctype="multipart/form-data">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <input type="file" id="uploadfimg" name="media[]" style="cursor: pointer;display: none;" multiple >
            </form>
        </div>
        <div class="card-content table-responsive">
            <table style="width: 100%;" class="table mediatable" id="FeaturedImg">
                <thead >
                    <th>Preview</th>
                    <th>Judul</th>
                    <th>Tanggal</th>
                    <th>Aksi</th>
                </thead>
            </table>
        </div>
    </div>
</div>
@endsection

Resources/views/admin/pages.blade.php
@extends('blog::layouts.master')

@section('content')
<div class="col-md-12">
<form method="post" action="{{ route('panel.page__delete__mass') }}" accept-charset="UTF-8">
    <a href="{{ route('panel.page__add') }}" class="btn btn-round btn-fill btn-info">New Page +<div class="ripple-container"></div></a>
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <input type="hidden" name="id" class="bulk-delete-id">
    <button type="sumbit" style="display: none;" class="btn btn-round btn-fill btn-danger bulk-delete-item">Delete <span class="bulk-delete-count"></span> Page</button>
</form>
<div class="card">
    <div class="card-header" data-background-color="green">
        <h4 class="title">Pages</h4>
        <p class="category">All Pages</p>
    </div>

    <div class="card-content table-responsive">
        <table class="table mydatatable" id="pages-table">
            <thead>
                <th>Title</th>
                <th>Author</th>
                <th>Published At</th>
                <th>Action</th>
            </thead>
        </table>
    </div>
</div>
</div>
@stop

Resources/views/admin/tagform.blade.php
@extends('blog::layouts.master')

@section('content')
<div class="col-md-12">
<div class="card">
    <div class="card-header" data-background-color="green">
        <h4 class="title">Tag</h4>
        <p class="category">{{ $act }} Tag</p>
    </div>
    <form method="post" action="{{ ($isEdit) ? route('panel.tag__update',$id) : route('panel.tag__save') }}" accept-charset="UTF-8">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <label class="control-label">Name</label>
            <input class="form-control" type="text" name="name" value="{{ $name }}">
        </div>
        <button type="submit" class="btn btn-success pull-right">Save</button>
        @if($isEdit)
        <a style="margin-right: 10px;" href="{{ route('panel.tag__delete',$id) }}" class="btn btn-danger pull-right" onclick="return confirm('Delete Tag?');">Delete</a>
        @endif
    </form>
</div>
</div>
@stop